-- SQLINES DEMO *** _DETAIL definition

-- SQLINES DEMO *** DBeaver CE
-- SQLINES DEMO *** iffer from actual native database DDL

-- Dr... SQLINES DEMO ***

-- SQLINES DEMO *** PORT_PERMIT_DETAIL;

-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE THE.EXPORT_PERMIT_DETAIL (
	EXPORT_PERMIT_DETAIL_NUMBER BIGINT,
	DESTINATION_COMPANY_NAME VARCHAR(52),
	TRANSPORT_NAME VARCHAR(26),
	ESTIMATED_SHIPPING_DATE TIMESTAMP(0),
	OTHER_PORT_OF_EXPORT VARCHAR(34),
	APPLICATION_DATE TIMESTAMP(0),
	RECEIVED_DATE TIMESTAMP(0),
	EXPORT_PERMIT_ISSUE_DATE TIMESTAMP(0),
	RECEIPT_NUMBER VARCHAR(50),
	EXPIRY_DATE TIMESTAMP(0),
	PERMIT_VOLUME DECIMAL(9,2),
	NUMBER_OF_PIECES BIGINT,
	FEE_IN_LIEU_VOLUME DECIMAL(11,2),
	FEDERAL_PERMIT_NUMBER VARCHAR(10),
	REMARKS VARCHAR(254),
	CLIENT_NUMBER VARCHAR(8),
	CLIENT_LOCN_CODE VARCHAR(2),
	EXEMPTION_NUMBER VARCHAR(8),
	ORG_UNIT_NO BIGINT,
	EXPORT_SCALE_METHOD_CODE VARCHAR(1),
	EXPORT_TRANSPORT_TYPE_CODE VARCHAR(1),
	EXPORT_PORT_OF_EXPORT_CODE VARCHAR(2),
	EXPORT_PERMIT_STATUS_CODE VARCHAR(3),
	EXPORT_COUNTRY_CODE VARCHAR(2),
	EXPORT_GROWTH_TYPE_CODE VARCHAR(1),
	OVERRIDE_FEE DECIMAL(9,2),
	OVERRIDE_COMMENT VARCHAR(254),
	OIC_REQUEST_PIECES BIGINT,
	OIC_REQUEST_VOLUME VARCHAR(9),
	OIC_APPLICATION_NUMBER BIGINT,
	AGENT_NUMBER VARCHAR(8),
	AGENT_LOCN_CODE VARCHAR(2),
	ENTRY_USERID VARCHAR(30),
	ENTRY_TIMESTAMP TIMESTAMP(0),
	UPDATE_USERID VARCHAR(30),
	UPDATE_TIMESTAMP TIMESTAMP(0),
	EXPORT_PRODUCT_TYPE_CODE VARCHAR(1),
	CONSTRAINT EPD_PK PRIMARY KEY (EXPORT_PERMIT_DETAIL_NUMBER),
	CONSTRAINT SYS_C00233033 CHECK ("EXPORT_PERMIT_DETAIL_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C00233034 CHECK ("APPLICATION_DATE" IS NOT NULL),
	CONSTRAINT SYS_C00233035 CHECK ("PERMIT_VOLUME" IS NOT NULL),
	CONSTRAINT SYS_C00233036 CHECK ("NUMBER_OF_PIECES" IS NOT NULL),
	CONSTRAINT SYS_C00233037 CHECK ("FEE_IN_LIEU_VOLUME" IS NOT NULL),
	CONSTRAINT SYS_C00233038 CHECK ("CLIENT_NUMBER" IS NOT NULL),
	CONSTRAINT SYS_C00233039 CHECK ("CLIENT_LOCN_CODE" IS NOT NULL),
	CONSTRAINT SYS_C00233040 CHECK ("ORG_UNIT_NO" IS NOT NULL),
	CONSTRAINT SYS_C00233041 CHECK ("EXPORT_SCALE_METHOD_CODE" IS NOT NULL),
	CONSTRAINT SYS_C00233042 CHECK ("EXPORT_PERMIT_STATUS_CODE" IS NOT NULL),
	CONSTRAINT SYS_C00233044 CHECK ("ENTRY_USERID" IS NOT NULL),
	CONSTRAINT SYS_C00233045 CHECK ("ENTRY_TIMESTAMP" IS NOT NULL)
);
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE UNIQUE INDEX EPD_PK ON THE.EXPORT_PERMIT_DETAIL (EXPORT_PERMIT_DETAIL_NUMBER);


-- SQLINES DEMO *** _DETAIL foreign keys

ALTER TABLE THE.EXPORT_PERMIT_DETAIL ADD CONSTRAINT EPD_CL_FK FOREIGN KEY (CLIENT_NUMBER,CLIENT_LOCN_CODE) REFERENCES THE.CLIENT_LOCATION(CLIENT_NUMBER,CLIENT_LOCN_CODE);
ALTER TABLE THE.EXPORT_PERMIT_DETAIL ADD CONSTRAINT EPD_CL_REPRESENTED_BY_FK FOREIGN KEY (AGENT_NUMBER,AGENT_LOCN_CODE) REFERENCES THE.CLIENT_LOCATION(CLIENT_NUMBER,CLIENT_LOCN_CODE);
ALTER TABLE THE.EXPORT_PERMIT_DETAIL ADD CONSTRAINT EPD_ECCD_FK FOREIGN KEY (EXPORT_COUNTRY_CODE) REFERENCES THE.EXPORT_COUNTRY_CODE(EXPORT_COUNTRY_CODE);
ALTER TABLE THE.EXPORT_PERMIT_DETAIL ADD CONSTRAINT EPD_EEA_FK FOREIGN KEY (OIC_APPLICATION_NUMBER) REFERENCES THE.EXPORT_EXEMPTION_APPLICATION(APPLICATION_NUMBER);
ALTER TABLE THE.EXPORT_PERMIT_DETAIL ADD CONSTRAINT EPD_EE_FK FOREIGN KEY (EXEMPTION_NUMBER) REFERENCES THE.EXPORT_EXEMPTION(EXEMPTION_NUMBER);
ALTER TABLE THE.EXPORT_PERMIT_DETAIL ADD CONSTRAINT EPD_EGTC_FK FOREIGN KEY (EXPORT_GROWTH_TYPE_CODE) REFERENCES THE.EXPORT_GROWTH_TYPE_CODE(EXPORT_GROWTH_TYPE_CODE);
ALTER TABLE THE.EXPORT_PERMIT_DETAIL ADD CONSTRAINT EPD_EPOEC_FK FOREIGN KEY (EXPORT_PORT_OF_EXPORT_CODE) REFERENCES THE.EXPORT_PORT_OF_EXPORT_CODE(EXPORT_PORT_OF_EXPORT_CODE);
ALTER TABLE THE.EXPORT_PERMIT_DETAIL ADD CONSTRAINT EPD_EPSC_FK FOREIGN KEY (EXPORT_PERMIT_STATUS_CODE) REFERENCES THE.EXPORT_PERMIT_STATUS_CODE(EXPORT_PERMIT_STATUS_CODE);
ALTER TABLE THE.EXPORT_PERMIT_DETAIL ADD CONSTRAINT EPD_EPTC_FK FOREIGN KEY (EXPORT_PRODUCT_TYPE_CODE) REFERENCES THE.EXPORT_PRODUCT_TYPE_CODE(EXPORT_PRODUCT_TYPE_CODE);
ALTER TABLE THE.EXPORT_PERMIT_DETAIL ADD CONSTRAINT EPD_ESMC_FK FOREIGN KEY (EXPORT_SCALE_METHOD_CODE) REFERENCES THE.EXPORT_SCALE_METHOD_CODE(EXPORT_SCALE_METHOD_CODE);
ALTER TABLE THE.EXPORT_PERMIT_DETAIL ADD CONSTRAINT EPD_ETTC_FK FOREIGN KEY (EXPORT_TRANSPORT_TYPE_CODE) REFERENCES THE.EXPORT_TRANSPORT_TYPE_CODE(EXPORT_TRANSPORT_TYPE_CODE);
ALTER TABLE THE.EXPORT_PERMIT_DETAIL ADD CONSTRAINT EPD_OU_FK FOREIGN KEY (ORG_UNIT_NO) REFERENCES THE.ORG_UNIT(ORG_UNIT_NO);
